version: '3.8'

services:
  database:
    image: mongo
    container_name: database_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/mongo
  
  app:
    build: .
    container_name: testing-heroku
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  mongodata:
    driver: local